name: "Build Site"
description: "Install frameworks and dependencies, then build the site."
author: "bmurty"
runs:
  using: composite
  steps:
    - name: Install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - name: Copy Deno binary to bin directory
      shell: bash
      run: |
        mkdir bin
        cp $(which deno) ./bin
    - name: Setup environment
      shell: bash
      run: ./bin/deno task setup
    - name: Build site
      shell: bash
      run: ./bin/deno task build
    - name: Upload build files
      uses: actions/upload-artifact@v6
      with:
        name: build-${{ github.sha }}
        overwrite: true
        include-hidden-files: true
        retention-days: 1
        compression-level: 9
        path: |
          bin/
          build/
          public/
          .env
branding:
  icon: "box"
  color: "green"
