name: "Build Site"
description: "Install frameworks and dependencies, then build the site."
author: "bmurty"
outputs:
  build-artifact-name:
    description: "The name of the artifact containing the build files from this action."
    value: ${{ steps.artifact.outputs.artifact-file-name }}
runs:
  using: composite
  steps:
    - name: Set build artifact name
      id: artifact
      shell: bash
      run: echo "artifact-file-name=build-$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
    - name: Set executable status on dev scripts
      shell: bash
      run: chmod +x ./dev/*.sh
    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.6.10
    - name: Setup environment
      shell: bash
      run: deno task setup
    - name: Build site
      shell: bash
      run: deno task build
    - name: Upload build files
      uses: actions/upload-artifact@v6
      with:
        name: ${{ steps.artifact.outputs.artifact-file-name }}
        overwrite: true
        include-hidden-files: true
        retention-days: 1
        compression-level: 9
        path: |
          build/
          public/
          .env
branding:
  icon: "box"
  color: "green"
