name: "Build Site"
description: "Install frameworks and dependencies, then build the site."
author: "bmurty"
runs:
  using: composite
  steps:
    - name: Install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - name: Setup environment
      shell: bash
      run: deno task setup
    - name: Install exiftool
      shell: bash
      run: sudo apt-get -y install exiftool
    - name: Build site
      shell: bash
      run: deno task build
branding:
  icon: "box"
  color: "green"
